### ISSUE TITLE
Shift mouse move is not applied

### ISSUE THREAD

**Issue by mmouchous-ledger** [Ledger-Donjon/visplot#7]
Shift+mouse move makes a roll operation on part of Line object depending on selected curves.
It assigns the line.pos object to new values, but this is ineffective visually, even with 'canvas.update' operation call.

self.line.set_data(pos=rolled_values) should be used instead.

For enhancement 
- horizontal offset should be applied instead of a roll.
- vertical offset may be possible (by hitting the ALT key).

**Comment by yhql** [comment]
Solved in #8
